import { getStateManager } from "./state";
import { getLogger } from "./logger";

/**
 * Optional "bring your own key" brain: when the user has set an Anthropic API
 * key, roasts are generated by Claude instead of the local model. The call is
 * made from the main process so the key never has to round-trip through the
 * renderer, and there's no CORS to fight.
 *
 * Privacy note: in this mode the behavioral context Clippy builds (app name,
 * non-sensitive window title, durations, time) is sent to Anthropic. Sensitive
 * and incognito titles are already stripped upstream (see ./privacy) before
 * they could ever reach here. Fully local mode (no key) sends nothing.
 */

// Sharp, fast, and witty — the sweet spot for one-liners.
const CLAUDE_MODEL = "claude-sonnet-4-6";
const REQUEST_TIMEOUT_MS = 20_000;

export function hasClaudeKey(): boolean {
  return !!(getStateManager().store.get("settings").claudeApiKey || "").trim();
}

/**
 * Generate one roast line via the Anthropic Messages API. Throws on missing
 * key, network error, or non-2xx response (callers fall back to local/canned).
 */
export async function generateCloud(
  systemPrompt: string,
  userPrompt: string,
): Promise<string> {
  const key = (getStateManager().store.get("settings").claudeApiKey || "").trim();
  if (!key) {
    throw new Error("No Claude API key set");
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: CLAUDE_MODEL,
        max_tokens: 200,
        system: systemPrompt,
        messages: [{ role: "user", content: userPrompt }],
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      const detail = await response.text().catch(() => "");
      throw new Error(
        `Claude API ${response.status}: ${detail.slice(0, 200)}`,
      );
    }

    const data = (await response.json()) as {
      content?: Array<{ type?: string; text?: string }>;
    };
    const text = (data.content || [])
      .filter((block) => block?.type === "text")
      .map((block) => block.text || "")
      .join("")
      .trim();

    return text;
  } catch (error) {
    getLogger().warn("Claude generation failed", error);
    throw error;
  } finally {
    clearTimeout(timer);
  }
}
