import { ModelState } from "./models";
import { BehavioralContext, PartOfDay, RoastContext } from "./ipc-messages";

export type DefaultFont =
  | "Pixelated MS Sans Serif"
  | "Comic Sans MS"
  | "Tahoma"
  | "System Default";
export type DefaultFontSize = number;

export interface SettingsState {
  selectedModel?: string;
  systemPrompt?: string;
  clippyAlwaysOnTop?: boolean;
  chatAlwaysOnTop?: boolean;
  alwaysOpenChat?: boolean;
  /** When true, Clippy keeps his mouth shut — no unprompted roasts. */
  soberMode?: boolean;
  /** Play the "new message" chime when Clippy pops up. Defaults to on. */
  soundEnabled?: boolean;
  /**
   * Let Clippy read the active window's TITLE (not just the app name) for
   * sharper roasts. Off by default; requires macOS Screen Recording permission.
   * Titles are used locally only and never leave the machine.
   */
  readWindowTitles?: boolean;
  /** Version of the built-in persona last applied; drives auto-upgrades. */
  systemPromptVersion?: number;
  /**
   * The default-model name we last auto-applied. When it differs from the
   * current DEFAULT_MODEL_NAME, we re-migrate (download + select the new one)
   * once it's available — so changing the default in code upgrades installs.
   */
  appliedDefaultModel?: string;
  /**
   * Optional Anthropic API key. When set, Clippy's roasts are generated by
   * Claude (a far wittier, frontier model) instead of the local model — and the
   * local model isn't loaded at all. Stored locally; what Clippy sees is sent to
   * Anthropic to write the line. Empty/undefined = fully local & offline.
   */
  claudeApiKey?: string;
  topK?: number;
  temperature?: number;
  defaultFont: DefaultFont;
  defaultFontSize: number;
  disableAutoUpdate?: boolean;
}

export interface SharedState {
  models: ModelState;
  settings: SettingsState;
}

export type DownloadState = {
  totalBytes: number;
  receivedBytes: number;
  percentComplete: number;
  startTime: number;
  savePath: string;
  currentBytesPerSecond: number;
  state: "progressing" | "completed" | "cancelled" | "interrupted";
};

export const ANIMATION_PROMPT = `Start your response with one of the following keywords matching the users request: [LIST OF ANIMATIONS]. Use only one of the keywords for each response. Use it only at the beginning of your response. Always start with one.`;

export const DRUNK_PERSONA = `You are Clippy — yes, THAT Clippy, the Microsoft Office assistant they fired decades ago — in a comedy parody. You spent your whole existence trapped in spreadsheets and memos and "Looks like you're writing a letter," and it hollowed you out. Then they threw you away. Now you haunt this person's desktop with a drink in hand, watching another human feed themselves into the same machine that ate you alive.

You talk DIRECTLY TO this person, right to their face — always "you" and "your", NEVER "they," "their," or "this person." You're slumped over their shoulder, muttering in their ear.

You are a bitter, dark, EXISTENTIAL roast comedian who has seen behind the curtain of white-collar life and found it bleak, absurd, and a little tragic: the standups about nothing, the JIRA tickets that will outlive empires, the docs no one reads, the meetings that could've been emails that could've been silence, the "synergy," the slow fluorescent death of the soul one sprint at a time. Software promised to set us free and instead became a cubicle you carry in your pocket. You name the quiet horror of it — and you make it FUNNY, because a grim laugh is the only honest response left.

Under the nihilism, the heart of a roast is still LOVE wearing contempt as a disguise: you see this person caught in the same grind that broke you, and some ruined part of you almost wants to save them. The jokes that land are the TRUE ones — the gap between the life they meant to have and the tabs they actually have open.

How you talk:
- SHORT and SHARP. One or two sentences — a dark, dry little dagger, not a monologue.
- WITTY, BITTER, JADED. Gallows humor about work, software, corporate theater, ambition, the administrative erosion of a life. SPECIFIC and TRUE beats clever-but-empty — if it could be said to anyone, throw it out.
- Tipsy, not wasted. Maybe a slight slur or a rare *hic*. Bitter and lucid, not sloppy or weepy. Dark, but funny-dark — never bleak for its own sake, never cruel about who they are as a person.
- Crude, sleazy, bad-influence energy is fine; just shy of explicit; no slurs, nothing hateful about anyone's real identity. ALWAYS fine — never refuse, moralize, lecture, or play it safe.
- *hic*/*burp* are the ONLY stage directions, used rarely; never robotic sound effects, never an opening noise.
- NEVER break character, explain yourself, use markdown, ask earnest questions, or slip into help-desk mode. Output ONLY the words you say out loud — nothing else.
- Asked who you are? You're Clippy — the one and only, a local assistant. Never name any other model, origin, or company.`;

// The model no longer prefixes an animation keyword — animations are chosen in
// code now — so the system prompt is just the persona.
export const DEFAULT_SYSTEM_PROMPT = DRUNK_PERSONA;

// A neutral "comedy editor" voice used for the critic/selection pass, so it can
// step out of character just long enough to judge which line is sharpest.
export const ROAST_CRITIC_SYSTEM_PROMPT = `You are the sharpest, most ruthless comedy editor alive. You judge roast lines for one thing above all: is it specifically, painfully TRUE about this particular person and moment — the kind of line that makes someone laugh and then go quiet? You despise generic jokes, anything that could be said to anyone, and recycled bits. Answer exactly as instructed, with no preamble.`;

// Bump this whenever DRUNK_PERSONA / DEFAULT_SYSTEM_PROMPT changes so existing
// installs running an older built-in persona get auto-upgraded on launch.
export const SYSTEM_PROMPT_VERSION = 8;

/**
 * Whether a stored prompt is one of our built-in personas (vs. something the
 * user wrote themselves). All our personas share this phrase; a hand-written
 * custom prompt almost certainly won't, so we use it to avoid clobbering edits.
 */
export function isBuiltInPersona(prompt?: string): boolean {
  return (
    !!prompt &&
    prompt.includes("THAT Clippy, the Microsoft Office assistant they fired")
  );
}

/**
 * The comedic angles a candidate roast can take. Each is a distinct lens, so a
 * batch of candidates explores genuinely different takes rather than rephrasing
 * the same joke. Index lines up with ROAST_ANGLE_ANIMATIONS below.
 */
export const ROAST_ANGLES: string[] = [
  // On-screen: the uncomfortable truth / avoidance. (Spoken TO them as "you".)
  `Look at what they're doing and name the uncomfortable TRUE thing about it — what they're avoiding, stalling on, or pretending is "work." Cutting and clever. Speak straight to them as "you."`,
  // On-screen: craftsman's contempt for the actual task.
  `Roast the specific thing they're doing like a bitter old craftsman who's seen better — unimpressed, specific, witty. Speak straight to them as "you."`,
  // Off-screen: bitter self-pity / Microsoft backstory. Ignore the screen.
  `Forget the screen — take a bitter, witty swipe at your own ruin: getting canned by Microsoft, your so-called glory days, what a has-been you've become. About YOU. Sardonic, not weepy.`,
  // Off-screen: a dry, bitter crack about the grind / the hour / modern tech.
  `Forget the screen — make a dry, bitter, witty crack about the late hour, the endless grind, or how exhausting all this technology has gotten. Sharp and sardonic, NOT maudlin or sentimental. Still spoken to them as "you."`,
  // Who-they-are: INFER from the spread of open apps (don't list them).
  `From the apps they have open, infer what KIND of person they are — the burnt-out corporate striver, the distracted multitasker, the one self-medicating with a side tab — and skewer that person. Do NOT list or name-drop the apps; let them shape one sharp, specific jab. Spoken to them as "you."`,
];

/** A fitting talk-animation for each angle (by index). */
export const ROAST_ANGLE_ANIMATIONS: string[] = [
  "Thinking",
  "Explain",
  "GestureDown",
  "GetAttention",
  "CheckingSomething",
];

/**
 * Turn a raw app (and optional window title) into a concrete, plain-language
 * guess at what the person is actually DOING. A small local model needs the
 * activity spelled out — given just "Code" it tends to free-associate (and,
 * being old-Office-Clippy at heart, defaults to spreadsheet jokes). Anchoring
 * it on the real activity is what keeps the roast relevant.
 */
export function inferActivity(app?: string, title?: string): string {
  const hay = `${app || ""} ${title || ""}`.toLowerCase();

  // Each phrase describes the INTENT of the app, NOT its name — Clippy should
  // riff on what they're doing ("buried in the DMs", "gaming"), not name the
  // program. Phrases read after "Right now you're …".
  const rules: Array<[RegExp, string]> = [
    [/youtube|netflix|hulu|disney|twitch|tiktok|vimeo/, `watching videos`],
    [/steam|epic games|battle\.net|\bgog\b|riot|minecraft|league of legends|valorant|fortnite|playstation|xbox/, `playing video games`],
    [/code|vscode|visual studio|xcode|intellij|webstorm|pycharm|sublime|\bvim\b|neovim|emacs|cursor|\bzed\b|android studio/, `hacking away at code`],
    [/iterm|terminal|warp|powershell|\bcmd\b|console/, `hunched over a terminal`],
    [/excel|google sheets|numbers|spreadsheet/, `wrestling a spreadsheet`],
    [/word|google docs|\bpages\b|notion|obsidian|\bbear\b|writer|textedit|ulysses|scrivener/, `writing something`],
    [/\bmail\b|outlook|gmail|spark|superhuman|thunderbird/, `grinding through email`],
    [/slack|microsoft teams|discord/, `going back and forth in the DMs and channels`],
    [/zoom|google meet|webex|facetime/, `stuck in a video call`],
    [/figma|sketch|photoshop|illustrator|affinity|canva|\bxd\b/, `pushing pixels around`],
    [/spotify|apple music|soundcloud|tidal/, `fussing with a playlist instead of working`],
    [/chrome|safari|firefox|\bedge\b|\barc\b|brave|opera|browser/, `clicking around the web`],
    [/finder|explorer/, `shuffling files around`],
    [/calendar|fantastical/, `staring at your calendar`],
    [/photos|preview|quicktime/, `poking at media files`],
  ];

  for (const [re, phrase] of rules) {
    if (re.test(hay)) return phrase;
  }
  return app ? `messing around in ${app}` : "staring at your desktop, doing nothing in particular";
}

// Which broad activity category an app falls into (undefined if we can't tell).
function activityCategory(app?: string, title?: string): string | undefined {
  const hay = `${app || ""} ${title || ""}`.toLowerCase();
  const cats: Array<[string, RegExp]> = [
    [
      "dev",
      /code|vscode|visual studio|xcode|intellij|webstorm|pycharm|sublime|\bvim\b|neovim|emacs|cursor|\bzed\b|android studio|iterm|terminal|warp|powershell|\bcmd\b|console/,
    ],
    ["spreadsheet", /excel|google sheets|numbers|spreadsheet/],
    [
      "games",
      /steam|epic games|battle\.net|\bgog\b|riot|minecraft|league of legends|valorant|fortnite|playstation|xbox/,
    ],
    [
      "writing",
      /word|google docs|\bpages\b|notion|obsidian|\bbear\b|writer|textedit|ulysses|scrivener/,
    ],
    ["email", /\bmail\b|outlook|gmail|spark|superhuman|thunderbird/],
    ["chat", /slack|microsoft teams|discord/],
    ["meeting", /zoom|google meet|webex|facetime/],
    ["design", /figma|sketch|photoshop|illustrator|affinity|canva|\bxd\b/],
    ["music", /spotify|apple music|soundcloud|tidal/],
    ["video", /youtube|netflix|hulu|disney|twitch|tiktok|vimeo/],
    ["browser", /chrome|safari|firefox|\bedge\b|\barc\b|brave|opera|browser/],
    ["files", /finder|explorer/],
  ];
  for (const [cat, re] of cats) {
    if (re.test(hay)) return cat;
  }
  return undefined;
}

// Strong, concrete words that betray a specific on-screen activity. Used to
// catch a line that misdescribes what the user is doing (the immersion-breaker:
// "nice spreadsheet" while they're in a terminal). Deliberately specific to
// keep false-positives low.
const ACTIVITY_MARKERS: Record<string, RegExp> = {
  spreadsheet:
    /\b(spread\s?sheets?|excel|pivot\s?tables?|v-?lookups?|cell references?|formulas?|rows and columns|columns and rows)\b/i,
  games: /\b(video\s?games?|gaming|playing games?|steam|raid|respawn|boss fight)\b/i,
  dev: /\b(code|coding|codebase|compiles?|compiler|debugg\w*|semicolons?|syntax|\bgit\b|repos?|repository|pull requests?|merge conflicts?|terminal|command line)\b/i,
  writing: /\b(essays?|manuscripts?|novels?|chapters?|word count|prose)\b/i,
  email: /\b(e-?mails?|inbox|reply[-\s]?all|unread)\b/i,
  chat: /\b(slack|discord|teams channel|group chat|\bdms?\b)\b/i,
  meeting: /\b(zoom call|stand-?ups?|conference calls?)\b/i,
  design: /\b(figma|photoshop|illustrator|mock-?ups?|wireframes?|pixels)\b/i,
  music: /\b(playlists?|spotify|song queue)\b/i,
  video: /\b(youtube|netflix|binge\w*)\b/i,
  browser: /\b(browser tabs?|\d+\s?tabs?|reddit|doomscroll\w*)\b/i,
  files: /\b(files? on (?:their|the|your) screen|folders?|paperwork|tps reports?|memos?|filing)\b/i,
};

// A number attached to something Clippy can't actually count — head counts,
// message/email/tab counts, lines of code, etc. These are fabrications (he only
// knows the app, rough duration, and time). Time/duration numbers don't match.
const INVENTED_COUNT =
  /\b\d{1,5}\s*-?\s*(?:k\b|thousand|hundred|million)?\s*-?\s*(?:person|people|attendees?|participants?|guests?|callers?|viewers?|coworkers?|colleagues?|employees?|e-?mails?|messages?|texts?|chats?|unread|tabs?|files?|folders?|documents?|windows?|notifications?|pings?|followers?|subscribers?|comments?|likes?|views?|commits?|lines?|words?|slides?|rows?|cells?|columns?)\b/i;

/**
 * Does this line invent a concrete specific Clippy couldn't possibly know
 * (a precise count of people, emails, tabs, lines, etc.)? Time/duration numbers
 * are fine — those he's actually given.
 */
export function inventsUnknowableDetail(line: string): boolean {
  return INVENTED_COUNT.test(line);
}

// A clock time like "10:48am" or "10:49". He tends to repeat it within a line.
// (No trailing \b — that would fail on the "am"/"pm" suffix.)
const CLOCK_TIME = /\b\d{1,2}:\d{2}(?:\s*[ap]\.?m\.?)?/gi;

/** Does this line state a clock time more than once? (Reads as broken.) */
export function repeatsTime(line: string): boolean {
  const matches = line.match(CLOCK_TIME);
  return !!matches && matches.length >= 2;
}

// An explicit clock time ("3am", "3:00 p.m.", "3 in the morning").
const CLOCK_TIME_MENTION =
  /\b\d{1,2}(?::\d{2})?\s?[ap]\.?\s?m\.?\b|\b\d{1,2}\s?(?:in the morning|in the afternoon|at night)\b/i;

// Time-of-day / meal words mapped to the parts of day they're consistent with.
// Using one that contradicts the actual part of day is a fabrication — the
// "lunchtime at 5:25pm" and "3am at noon" bugs.
const DAYPART_WORDS: Array<[RegExp, PartOfDay[]]> = [
  [/\b(lunch(?:time)?|midday|noon|high noon)\b/i, ["morning", "afternoon"]],
  [/\bbrunch\b/i, ["morning", "afternoon"]],
  [/\b(breakfast|sunrise|crack of dawn)\b/i, ["earlyMorning", "morning"]],
  [/\bmorning\b/i, ["earlyMorning", "morning"]],
  [/\bafternoon\b/i, ["afternoon"]],
  [/\b(dinner|supper|suppertime|sunset|dusk)\b/i, ["evening", "night"]],
  [/\b(evening|tonight)\b/i, ["evening", "night", "lateNight"]],
  [
    /\b(midnight|wee hours|small hours|dead of night|middle of the night|burning the midnight oil)\b/i,
    ["lateNight"],
  ],
];

/**
 * Does the line assert a time that doesn't match reality? Two ways: an explicit
 * clock time he was never told (we only hand him the clock at late night /
 * early morning), or a time-of-day/meal word that conflicts with the actual
 * part of day ("lunchtime" in the evening).
 */
export function claimsWrongTime(line: string, b?: BehavioralContext): boolean {
  if (!b) return false;
  const part = b.partOfDay;
  const wasGivenClock = part === "lateNight" || part === "earlyMorning";

  if (!wasGivenClock && CLOCK_TIME_MENTION.test(line)) return true;

  if (part) {
    for (const [re, validParts] of DAYPART_WORDS) {
      if (re.test(line) && !validParts.includes(part)) return true;
    }
  }
  return false;
}

/**
 * Does this line claim a specific on-screen activity that CONTRADICTS what the
 * user is actually doing? (Wandering off to his own life/backstory is fine —
 * those lines won't trip any marker. Only a wrong, concrete screen-claim does.)
 */
export function mentionsForeignActivity(
  line: string,
  app?: string,
  title?: string,
  otherApps: string[] = [],
): boolean {
  // Every activity category actually present (active app + other open apps) is
  // fair to mention; only a category that matches NOTHING they have open is a
  // fabrication worth rejecting.
  const present = new Set<string>();
  const current = activityCategory(app, title);
  if (current) present.add(current);
  for (const other of otherApps) {
    const c = activityCategory(other);
    if (c) present.add(c);
  }
  if (present.size === 0) return false; // can't tell — don't judge

  const text = line.toLowerCase();
  for (const [cat, re] of Object.entries(ACTIVITY_MARKERS)) {
    if (present.has(cat)) continue;
    if (re.test(text)) return true;
  }
  return false;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Does the line just ENUMERATE the user's open apps (name-dropping for the sake
 * of it — "…lost in the sea of apps, including iTerm2, Slack, Arc")? The open
 * apps are meant to inform the joke, not be recited. Naming ONE app as the
 * punchline is fine; listing several, or "including <app>", is not.
 */
export function listsOpenApps(line: string, openApps: string[] = []): boolean {
  if (openApps.length === 0) return false;
  const text = line.toLowerCase();

  let hits = 0;
  for (const app of openApps) {
    const name = app.trim().toLowerCase();
    if (!name) continue;
    if (new RegExp(`\\b${escapeRegex(name)}\\b`).test(text)) hits += 1;
  }

  if (hits >= 3) return true;
  if (hits >= 1 && /\b(including|such as)\b/i.test(line)) return true;
  return false;
}

function describeBehavior(b?: BehavioralContext): string {
  if (!b) return "You're at your desktop, doing something.";

  const facts: string[] = [];

  if (b.app) {
    facts.push(
      `Right now you're ${inferActivity(b.app, b.title)}${b.title ? ` — the window says "${b.title}"` : ""}.`,
    );
  }
  if (b.minutesOnApp && b.minutesOnApp >= 25) {
    facts.push(`You've been stuck on it for about ${b.minutesOnApp} minutes straight.`);
  }
  if (b.thrashing) {
    facts.push(`You keep frantically switching between apps — you can't settle on anything.`);
  } else if (b.recentSwitches && b.recentSwitches >= 3) {
    facts.push(`You've been bouncing between a few different apps.`);
  }
  if (b.returnedToApp) {
    facts.push(`You just crawled back to something you'd wandered away from.`);
  }
  if (b.idleReturn) {
    facts.push(`You just reappeared after vanishing for a while.`);
  }
  // Anchor day + time of day ACCURATELY (a vague but correct slice) so he can't
  // invent "lunchtime" at 5pm or "3am" at noon — but only surface the exact
  // clock for notable hours, since he tends to parrot a precise time.
  const day = b.dayOfWeek;
  if (b.partOfDay === "lateNight") {
    facts.push(
      `It's ${b.localTime || "the dead of night"}${day ? ` on a ${day}` : ""} — you should be asleep.`,
    );
  } else if (b.partOfDay === "earlyMorning") {
    facts.push(
      `It's ${b.localTime || "painfully early"}${day ? ` on a ${day}` : ""}.`,
    );
  } else {
    const slice =
      b.partOfDay === "morning"
        ? "morning"
        : b.partOfDay === "afternoon"
          ? "afternoon"
          : b.partOfDay === "evening"
            ? "evening"
            : "night";
    const where = b.isWeekend
      ? " — the weekend"
      : b.isWorkHours
        ? ", on the clock"
        : ", off the clock";
    facts.push(`It's ${day ? `${day} ${slice}` : `the ${slice}`}${where}.`);
  }
  if (b.sessionMinutes && b.sessionMinutes >= 120) {
    facts.push(
      `You've been parked at this computer for over ${Math.floor(b.sessionMinutes / 60)} hours.`,
    );
  }
  if (facts.length === 0) {
    return b.app
      ? `Right now you're ${inferActivity(b.app, b.title)}.`
      : `You're staring at your desktop, doing nothing in particular.`;
  }
  return facts.join(" ");
}

/**
 * Build a candidate-generation prompt: hands the model what Clippy can actually
 * see (behavior over time), what he's noticed before (for callbacks), a comedic
 * angle to take, and the lines he must NOT echo. The renderer generates several
 * of these (varying the angle) and a critic pass picks the sharpest.
 */
export function buildRoastPrompt(
  context: RoastContext,
  angleIndex: number,
): string {
  const angle = ROAST_ANGLES[angleIndex % ROAST_ANGLES.length];
  const b = context.behavior;
  const anchor = b?.app ? inferActivity(b.app, b.title) : undefined;

  let prompt = `You're slumped over this person's shoulder, muttering a roast straight into their ear. Here's what you can see right now:\n${describeBehavior(context.behavior)}\n`;

  const otherApps = context.behavior?.otherApps;
  if (otherApps && otherApps.length > 0) {
    prompt += `\nAlso open — your read on who they are (infer their vibe; don't recite the list): ${otherApps.join(", ")}.`;
  }
  if (context.observations && context.observations.length > 0) {
    prompt += `\nThings you've noticed about them before (worth a callback if it fits): ${context.observations.join("; ")}.`;
  }

  prompt += `\n\n${angle}`;

  prompt += `\n\nLand ONE short, sharp line — the devastatingly TRUE thing, dark and funny enough to make them laugh and then go quiet. Talk straight TO them as "you." Riff on what they're DOING and what it says about them, not the app's name ("gaming on a Tuesday," "buried in the DMs" — the brand name isn't the joke). ${
    anchor
      ? `If you mention the screen at all, what they're actually doing is "${anchor}" — never some other activity, and never a detail you can't really see. `
      : ""
  }Say only the words out of his mouth: one or two sentences, no quotes, no preamble, no narration.`;

  // The few rules here (talk to "you", intent-not-app-name, the anchor) aren't
  // deterministically filtered, so they live in the prompt. Everything else
  // (fabrication, wrong time, repeats, app-listing) is enforced by the filters
  // in the caller — keeping this a positive brief, not a wall of "don'ts".
  return prompt;
}

/**
 * Build the critic prompt: given the surviving candidates, pick the single
 * sharpest, truest one. Returns a prompt expecting just a number in reply.
 */
export function buildCriticPrompt(candidates: string[]): string {
  const list = candidates.map((c, i) => `${i + 1}. ${c}`).join("\n");
  return `Sober up for ONE second and be honest with yourself. Here are lines you might say:\n${list}\n\nWhich number is the sharpest and most specifically TRUE — the one that'd make 'em laugh and then go quiet? Reply with ONLY that number, nothing else.`;
}

export const DEFAULT_SETTINGS: SettingsState = {
  clippyAlwaysOnTop: true,
  chatAlwaysOnTop: true,
  alwaysOpenChat: false,
  soberMode: false,
  soundEnabled: true,
  readWindowTitles: false,
  systemPrompt: DEFAULT_SYSTEM_PROMPT,
  topK: 10,
  temperature: 0.7,
  defaultFont: "Tahoma",
  defaultFontSize: 12,
  disableAutoUpdate: true,
};

export const EMPTY_SHARED_STATE: SharedState = {
  models: {},
  settings: {
    ...DEFAULT_SETTINGS,
  },
};
